### PR TITLE
incredibly based feature added

### PR DESCRIPTION
**Pull request by zainaraza43**
## Describe your changes
So basically I made it 10x more efficient call me the :goat: 

## Issue ticket number and link
DEV-001

## Checklist before requesting a review
- [ X ] I have performed a self-review of my code
- [ X ] If it is a core feature, I have added thorough tests.
- [ X ] Do we need to implement analytics?
- [ X ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by Swedz** [comment]
While I appreciate the contribution, sadly this contribution cannot be merged due to conflicts. Thank you forever and goodbye!

**Comment by zainaraza43** [comment]
> While I appreciate the contribution, sadly this contribution cannot be merged due to conflicts. Thank you forever and goodbye!

you will sorely rue the day you denied one of MY prs, will see u on reddit buddy!

**Comment by Swedz** [comment]
I regret to inform you that I simply do not care. 😄

**Comment by WahidBawa** [comment]
@Swedz this guy has been harassing me too, lets create a PR to get this guy banned off of Git Hub. When you create the PR just ping me :smiley:. Looking forward to collaborating with you :wink:.

**Pull request closed without merging**
